create table events(
                       id BIGINT generated by default as identity not null,
                       topic varchar(50) not null,
                       description character varying(300) not null,
                       organizer character varying(50) not null,
                       event_time timestamp not null default now(),
                       location character varying(100) not null,
                       created_at timestamp not null,
                       updated_at timestamp not null,
                       constraint events_pk PRIMARY KEY (id)
);
